# Generated by Django 4.2.17 on 2025-01-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='title',
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_blogs.blogmodel', verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='comment',
            field=models.CharField(max_length=128, verbose_name='comment'),
        ),
    ]
