# Generated by Django 4.2.17 on 2025-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0002_remove_blogauthormodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app_blogs.blogtagmodel', verbose_name='tags'),
        ),
    ]
