# Generated by Django 4.2.17 on 2025-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0003_blogcommentmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app_blogs.blogtagmodel', verbose_name='tags'),
        ),
    ]
